### ISSUE TITLE
More strict link handling

### ISSUE THREAD

**Issue by lekterable** [MichaelDeBoey/gatsby-remark-embedder#11]
- `gatsby-remark-embedder` version: 1.1.2
- `node` version: v10.16.0
- `npm` (or `yarn`) version: 6.9.0

What you did:

Used a markdown syntax of pasting a link

`<https://www.youtube.com/watch?v=dQw4w9WgXcQ>`

or

`[https://www.youtube.com/watch?v=dQw4w9WgXcQ](https://www.youtube.com/watch?v=dQw4w9WgXcQ)`

What happened:

Links are getting transformed into a video

Suggested solution:

I would transform only those links which are at the beginning of the new line to make sure that users have a way of posting an actual link if they want to.

**Comment by MichaelDeBoey** [comment]
Hi @lekterable!

Thanks for reporting this.

Can you provide me with a reproduction link (CodeSandbox) or repo so I can dig into this further, please? 🤔

**Comment by MichaelDeBoey** [comment]
Hi @lekterable!

If I understand your request correctly, I think this isn't something that can be fixed.
If you look at the [AST that's created](https://astexplorer.net/#/gist/5d779885c7f454eca86b19cac67810b9/2972d670d4fc3845dfa096158f103eefa5a99211), you'll see that each link will give you the exact same Node.
This means there's no way to know the difference between all 3 of them.

Since this plugin is looking if there's a link on a single line and is the only thing on that line, I suggest you don't put it on a single line or you put some extra braces (`()`) around it.

**Comment by lekterable** [comment]
Hey @MichaelDeBoey , sorry I wasn't much help in creating a sandbox for those issues and huge thanks for fixing the first one! I've looked at the AST you've linked and I think I might see a way of tackling this. 
Every node has a property position -> start -> column which from what I understand indicates where exactly in the text this given link was found.
```
"children": [
            {
              "type": "text",
              "value": "https://youtube.com/watch?v=dQw4w9WgXcQ",
              "position": {
                "start": {
                  "line": 1,
                  "column": 1,
                  "offset": 0
                },
                "end": {
                  "line": 1,
                  "column": 40,
                  "offset": 39
                },
                "indent": []
              }
            }
          ],
```

If that's true we could make sure that the plugin only cares about those links that have this property equal to `1` as it would rule out both this:

`<https://www.youtube.com/watch?v=dQw4w9WgXcQ>`

and 

`[https://www.youtube.com/watch?v=dQw4w9WgXcQ](https://www.youtube.com/watch?v=dQw4w9WgXcQ)`

because for them it will always be `2` :

```
"children": [
            {
              "type": "text",
              "value": "https://youtube.com/watch?v=dQw4w9WgXcQ",
              "position": {
                "start": {
                  "line": 3,
                  "column": 2,
                  "offset": 42
                },
                "end": {
                  "line": 3,
                  "column": 41,
                  "offset": 81
                },
                "indent": []
              }
            }
          ],
```

Let me know if that makes sense and if that's the direction you would like to go, if so I'd love to work on a PR for it :)

**Comment by MichaelDeBoey** [comment]
@lekterable That would indeed be a possible solution for what you're suggesting.

Since using pure markdown those 3 lines are seen as exactly the same (people expect them to give the same output), I'm not going to do anything about this.

I hope you understand my point of view and why I'm not going to include your proposal into the plugin.

If you have some future improvements, I'm happy to look into them tho! 🙂
