### ISSUE TITLE
Support embed outside gatsby using remark plugins

### ISSUE THREAD

**Issue by osiux** [MichaelDeBoey/gatsby-remark-embedder#136]
Wanted to gauge the interest on making this available outside Gatsby ecosystem. I'm working on a nextjs blog where I would love to have this automatic embeds, and I think its pretty straightforward with the way the gatsby plugin works.

For distribution I think on two scenarios, the first would be to make this a multi repo with two packages, current `gatsby-remark-embedder` and a new `remark-embedder`. This later package would be the one with all functionality, distributed as remark plugin, gatsby plugin would just make use of it. This can be done maybe using [lerna](https://lerna.js.org/). An example of this structure I found is https://github.com/kevin940726/remark-codesandbox

The other options is to keep this as is, and just add a new `remark-embedder.js` file which should be used as a remark plugin whenever needed.

Wanted to ask first before working on this. Let me know!

**Comment by MichaelDeBoey** [comment]
Hey @osiux! 👋

To be honest, I've already been thinking about extracting the core so I could re-use that part and support NextJS, ...
I currently lack some time, but this is definitely something I want to look into in the (near) future 🙂

**Comment by wooorm** [comment]
Hi all! I’m coming to this conversation as the maintainer of remark et al, and would also like to see a standalone project, for example so that it can be used directly with remark, but also for example with [Next](https://nextjs.org) or [MDSveX](https://github.com/pngwn/MDsveX).
It seems like there’s only a small layer of Gatsby-specific code?

For the remark part, there are certain Gatsby-esque things in this project, such as using raw HTML strings: https://github.com/MichaelDeBoey/gatsby-remark-embedder/blob/5f426ccc76b2b2eb81e7987263969dee8d15dbc5/src/transformers/Pinterest.js#L31
That works fine if you’re indeed going to make HTML, and Gatsby (and MDX@1) are doing some magic there, but with MDX@2 we’re going remove it in favor of an AST: [hast](https://github.com/syntax-tree/hast) ([rehype](https://github.com/rehypejs/rehype)) (which the other stuff made on remark already supports).

How can I help?

**Comment by MichaelDeBoey** [comment]
Hi @wooorm! 👋

Awesome that you're wanting to help out! 👊

Can we maybe have a chat somewhere (Twitter DM or so), so you can elaborate a bit more about your remarks (no pun intended) please?
I assume MDX@1 does **only** accept an HTML string, but `remark` & MDX@2 **only** accept an AST? 🤔

**Comment by osiux** [comment]
I'm still very interested on this, so if I can help, please feel free to include me in the conversation!

**Comment by MichaelDeBoey** [comment]
@osiux I'm already working on an extracted core-package so it can be used on multiple platforms 😉

**Comment by osiux** [comment]
Came to post that I used a workaround ([1](https://github.com/osiux/osiux.ws/blob/main/src/utils/embedder.ts), [2](https://github.com/osiux/osiux.ws/blob/main/pages/blog/%5Bslug%5D.tsx#L99)) to use this on a nextjs site and saw Kent's PR! Gonna follow progress over there! Should we close this issue?

**Comment by kentcdodds** [comment]
Checkout https://github.com/remark-embedder/core

This package will eventually be migrated to use that when @MichaelDeBoey gets around to it.

You'll also probably want to use https://github.com/remark-embedder/transformer-oembed

That handles most of what this package does I think.

**Comment by MichaelDeBoey** [comment]
@osiux I'm currently in the middle of some renovations at my home, but I'm planning to migrate this plugin (and all transformers) over to the new @remark-embedder way of doing things very soon.

**Comment by osiux** [comment]
@MichaelDeBoey sounds good! Will take a look to see how I can help :)
