### ISSUE TITLE
Support custom transformers

### ISSUE THREAD

**Issue by kentcdodds** [MichaelDeBoey/gatsby-remark-embedder#42]
The way that I organized this originally was to make it so people could create custom transformers (think of it as a form of [Inversion of Control](https://kcd.im/ioc)). I think an API like this might be nice:

```javascript
// In your gatsby-config.js
import someSiteTransformer from './src/some-site-transformer'

// config...
plugins: [
  {
    resolve: `gatsby-transformer-remark`,
    options: {
      plugins: [
        {
          resolve: 'gatsby-remark-embedder',
          options: {
            customTransformers: [
              someSiteTransformer,
            ],
          },
        },
      ],
    },
  },
];
```

I don't think it should be too much of a challenge to implement. Thoughts?

**Comment by sigvei** [comment]
I realise this issue is closed, but I am stumped as to how this is supposed to work, and maybe it's not just me?

The documentation tells me to `import transformer from './src/my_transformer.js`, but that is not a legal statement in `gatsby-config.js`: `Cannot use import statement outside a module`, says node (both 13.6 and 12.14).

If i try to `require` the transformer instead, node just complains that `export` is an illegal statement.

I also tried to make my entire site a module (by adding `"type": "module"` to `package.json`, but that broke gatsby.

I am sure it's just me being stupid, but maybe the documentation needs some hint on how to configure this properly?

Thanks for the plugin, by the way. It works very well, and the API for adding new providers looks very promising.

**Comment by MichaelDeBoey** [comment]
@sigvei Thanks for bringing up this issue.
I've updated the example.

If that's not clear enough, you can always send in a PR to make it more clear. 🙂
If you take a look at kentcdodds/kentcdodds.com#348, you'll see how I've implemented a custom transformer there. 😉
